### ISSUE TITLE
External gromacs SIF image 

### ISSUE THREAD

**Issue by mmagithub** [dptech-corp/Uni-GBSA#29]
Hi,

The tool seems to require a pre-compiled gromacs (gmx) to work from the container. Is it possible to provide the absolute path of an external gromacs container (as a docker or a singularity image) as a command line argument such that it can use it instead of looking locally for an installed gmx binaries,

Thanks

**Comment by mmagithub** [comment]
I tried aliasing the gmx:
alias gmx='singularity run -B $PWD -B /home/marawan/Desktop/images_executables/ --nv /path_to_gromacs_image/gromacs.sif gmx'

but still I got this error:

**ERROR:root:Not found gmx or gmx_mpi.**

**Comment by Aunity** [comment]
Hi, 

The **Uni-GBSA** need an executable **gmx** or **gmx_mpi** in the environment variable. If the executable **gmx** and **gmx_mpi** commands are not found, it will raise the error: ``ERROR:root:Not found gmx or gmx_mpi.`` 

For your situation, I recommend **two methods** to solve your problem: 

**Method 1:**
Using the ```conda create -n gbsa -c conda-forge acpype openmpi mpi4py gromacs``` to install the dependencies required by Uni-GBSA.


**Method 2:**
Write the command line 
```bash
singularity run -B $PWD -B /home/marawan/Desktop/images_executables/ --nv /path_to_gromacs_image/gromacs.sif gmx $@
``` 
into a file named **gmx**, and give this file an executable permission through ```chmod +x gmx```. Then put the **gmx** file in ```/anywhere/path/```, and add this folder to **PATH** by ```export PATH=/anywhere/path/:$PATH```.
