### ISSUE TITLE
ERROR run mdrun minim.tpr.

### ISSUE THREAD

**Issue by kdpan** [dptech-corp/Uni-GBSA#44]
This is a very good job, but I encountered the following error while running the first example：
`$ unigbsa-pipeline -i example/1ceb/1ceb_protein.pdb -l example/1ceb/1ceb_ligand.sdf -o BindingEnergy.csv`
The following is the error message：

> 

> 01/18/2024 21:29:59 PM - INFO - Build protein topology.
> 
> 01/18/2024 21:30:00 PM - INFO - Build ligand topology: 1ceb_ligand
> 01/18/2024 21:30:04 PM - INFO - Running energy minimization: 1ceb_ligand
> sh: line 1: 19327 Segmentation fault      gmx mdrun -v -deffnm minim -nt 1 -ntmpi 1 >> gromacs.log 2>&1
> gmx mdrun -v -deffnm minim -nt 1 -ntmpi 1 
> Generating 1-4 interactions: fudge = 0.5
> Number of degrees of freedom in T-Coupling group rest is 4479.00
> The integrator does not provide a ensemble temperature, there is no system ensemble temperature
> 
> NOTE 2 [file /home/panfulu/anaconda3/envs/uni/lib/python3.8/site-packages/unigbsa/simulation/mdp/minim.mdp]:
>   The optimal PME mesh load for parallel simulations is below 0.5
>   and for highly parallel simulations between 0.25 and 0.33,
>   for higher performance, increase the cut-off and the PME grid spacing.
> 
> 
> 
> There were 2 NOTEs
> 
> Back Off! I just backed up minim.tpr to ./#minim.tpr.1#
> 
> GROMACS reminds you: "Ubiquitin's just a rock" (Berk Hess)
> 
> Setting the LD random seed to -697645185
> 
> Generated 741 of the 741 non-bonded parameter combinations
> 
> Generated 741 of the 741 1-4 parameter combinations
> 
> Excluding 3 bonded neighbours molecule type 'MOL'
> 
> Excluding 3 bonded neighbours molecule type 'system1'
> 
> Excluding 3 bonded neighbours molecule type 'SOL'
> Analysing residue names:
> There are:     1      Other residues
> There are:    80    Protein residues
> There are:    81      Water residues
> Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
> Analysing Protein...
> 
> The largest distance between excluded atoms is 0.491 nm between atom 1244 and 1251
> Calculating fourier grid dimensions for X Y Z
> Using a fourier grid of 52x42x40, spacing 0.112 0.118 0.110
> 
> Estimate for the relative computational load of the PME mesh part: 0.68
> 
> This run will generate roughly 0 Mb of data
>                 :-) GROMACS - gmx mdrun, 2023.1-conda_forge (-:
> 
> Executable:   /home/panfulu/anaconda3/envs/uni/bin.AVX2_256/gmx
> Data prefix:  /home/panfulu/anaconda3/envs/uni
> Working dir:  /home/panfulu/project/Uni-GBSA/1ceb_ligand/complex.GMX
> Command line:
>   gmx mdrun -v -deffnm minim -nt 1 -ntmpi 1
> 
> Traceback (most recent call last):
>   File "/home/panfulu/anaconda3/envs/uni/lib/python3.8/site-packages/unigbsa/pipeline.py", line 149, in single
>     minimgro, outtop = engine.run_to_minim(grofile, topfile,
>   File "/home/panfulu/anaconda3/envs/uni/lib/python3.8/site-packages/unigbsa/simulation/mdrun.py", line 385, in run_to_minim
>     minipdb = self.gmx_minim(ionspdb, topfile, mdpfile=os.path.join(MDPFILESDIR, 'minim.mdp'), nt=nt)
>   File "/home/panfulu/anaconda3/envs/uni/lib/python3.8/site-packages/unigbsa/simulation/mdrun.py", line 200, in gmx_minim
>     outfile = self._mdrun(outtpr, nt)
>   File "/home/panfulu/anaconda3/envs/uni/lib/python3.8/site-packages/unigbsa/simulation/mdrun.py", line 80, in _mdrun
>     raise Exception('ERROR run mdrun %s. See the logfile for details %s'%(tprfile, os.path.abspath(self.gmxlog)))
> Exception: ERROR run mdrun minim.tpr. See the logfile for details /home/panfulu/project/Uni-GBSA/1ceb_ligand/complex.GMX/gromacs.log
> 01/18/2024 21:30:06 PM - WARNING - Failed to run simulation for ligand: 1ceb_ligand

The following is the information in the gromacs.log file:

>                :-) GROMACS - gmx editconf, 2023.1-conda_forge (-:
> 
> Executable:   /home/panfulu/anaconda3/envs/uni/bin.AVX2_256/gmx
> Data prefix:  /home/panfulu/anaconda3/envs/uni
> Working dir:  /home/panfulu/project/Uni-GBSA/1ceb_ligand/complex.GMX
> Command line:
>   gmx editconf -f /home/panfulu/project/Uni-GBSA/1ceb_ligand/complex.pdb -o box.pdb -bt triclinic -d 0.900000
> 
> 
> Back Off! I just backed up box.pdb to ./#box.pdb.1#
> 
> GROMACS reminds you: "Ubiquitin's just a rock" (Berk Hess)
> 
> Note that major changes are planned in future for editconf, to improve usability and utility.
> Read 1494 atoms
> Volume: 1272.11 nm^3, corresponds to roughly 572400 electrons
> No velocities found
>     system size :  3.999  3.165  2.596 (nm)
>     center      :  1.793 -0.188  3.244 (nm)
>     box vectors : 13.956 11.878  7.674 (nm)
>     box angles  :  90.00  90.00  90.00 (degrees)
>     box volume  :1272.11               (nm^3)
>     shift       :  1.106  2.670 -1.046 (nm)
> new center      :  2.900  2.482  2.198 (nm)
> new box vectors :  5.799  4.965  4.396 (nm)
> new box angles  :  90.00  90.00  90.00 (degrees)
> new box volume  : 126.57               (nm^3)
>                 :-) GROMACS - gmx grompp, 2023.1-conda_forge (-:
> 
> Executable:   /home/panfulu/anaconda3/envs/uni/bin.AVX2_256/gmx
> Data prefix:  /home/panfulu/anaconda3/envs/uni
> Working dir:  /home/panfulu/project/Uni-GBSA/1ceb_ligand/complex.GMX
> Command line:
>   gmx grompp -f /home/panfulu/anaconda3/envs/uni/lib/python3.8/site-packages/unigbsa/simulation/mdp/minim.mdp -c /home/panfulu/project/Uni-GBSA/1ceb_ligand/complex.GMX/box.pdb -r /home/panfulu/project/Uni-GBSA/1ceb_ligand/complex.GMX/box.pdb -o minim.tpr -p /home/panfulu/project/Uni-GBSA/1ceb_ligand/complex.GMX/complex.top -maxwarn 5
> 
> Ignoring obsolete mdp entry 'ns_type'
> 
> NOTE 1 [file /home/panfulu/anaconda3/envs/uni/lib/python3.8/site-packages/unigbsa/simulation/mdp/minim.mdp]:
>   With Verlet lists the optimal nstlist is >= 10, with GPUs >= 20. Note
>   that with the Verlet scheme, nstlist has no effect on the accuracy of
>   your simulation.
> 
> Generating 1-4 interactions: fudge = 0.5
> Number of degrees of freedom in T-Coupling group rest is 4479.00
> The integrator does not provide a ensemble temperature, there is no system ensemble temperature
> 
> NOTE 2 [file /home/panfulu/anaconda3/envs/uni/lib/python3.8/site-packages/unigbsa/simulation/mdp/minim.mdp]:
>   The optimal PME mesh load for parallel simulations is below 0.5
>   and for highly parallel simulations between 0.25 and 0.33,
>   for higher performance, increase the cut-off and the PME grid spacing.
> 
> 
> 
> There were 2 NOTEs
> 
> Back Off! I just backed up minim.tpr to ./#minim.tpr.1#
> 
> GROMACS reminds you: "Ubiquitin's just a rock" (Berk Hess)
> 
> Setting the LD random seed to -697645185
> 
> Generated 741 of the 741 non-bonded parameter combinations
> 
> Generated 741 of the 741 1-4 parameter combinations
> 
> Excluding 3 bonded neighbours molecule type 'MOL'
> 
> Excluding 3 bonded neighbours molecule type 'system1'
> 
> Excluding 3 bonded neighbours molecule type 'SOL'
> Analysing residue names:
> There are:     1      Other residues
> There are:    80    Protein residues
> There are:    81      Water residues
> Analysing residues not classified as Protein/DNA/RNA/Water and splitting into groups...
> Analysing Protein...
> 
> The largest distance between excluded atoms is 0.491 nm between atom 1244 and 1251
> Calculating fourier grid dimensions for X Y Z
> Using a fourier grid of 52x42x40, spacing 0.112 0.118 0.110
> 
> Estimate for the relative computational load of the PME mesh part: 0.68
> 
> This run will generate roughly 0 Mb of data
>                 :-) GROMACS - gmx mdrun, 2023.1-conda_forge (-:
> 
> Executable:   /home/panfulu/anaconda3/envs/uni/bin.AVX2_256/gmx
> Data prefix:  /home/panfulu/anaconda3/envs/uni
> Working dir:  /home/panfulu/project/Uni-GBSA/1ceb_ligand/complex.GMX
> Command line:
>   gmx mdrun -v -deffnm minim -nt 1 -ntmpi 1
>

**Comment by Aunity** [comment]
Have you tried running this command directly? 
`gmx mdrun -v -deffnm minim -nt 1 -ntmpi 1`

**Comment by kdpan** [comment]
I tried using this command and obtained the following output information：


>         :-) GROMACS - gmx mdrun, 2023.1-conda_forge (-:
> 
> Executable:   /home/panfulu/anaconda3/envs/uni/bin.AVX2_256/gmx
> Data prefix:  /home/panfulu/anaconda3/envs/uni
> Working dir:  /home/panfulu/project/Uni-GBSA/1ceb_ligand/complex.GMX
> Command line:
>   gmx mdrun -v -deffnm minim -nt 1 -ntmpi 1
> 
> Segmentation fault

**Comment by Aunity** [comment]
This error may casued by the gromacs version. Try `conda install gromacs==2022.4`  to change the gromacs version to see if it works.

**Comment by kdpan** [comment]
It is OK. Thank you very much!
