### ISSUE TITLE
Question about the installation of uni-GBSA by conda

### ISSUE THREAD

**Issue by Tangbbmc** [dptech-corp/Uni-GBSA#46]
Previously, I have installed Gromacs and gmx_MMPBSA on my Ubuntu system. Then, when I will install uni-GBSA by conda, what are the issues I need to be aware of?

**Comment by Aunity** [comment]
One important thing is you need to install the mpi4py by `conda install mpi4py` before install uni-gbsa. Cause `pip install unigbsa` will use the pypi mpi4py which will cause install error.
