### ISSUE TITLE
Errors when installing by conda

### ISSUE THREAD

**Issue by zaixizhang** [dptech-corp/Uni-GBSA#50]
Hi,

I tried to follow the readme to install by conda. When running pip install unigbsa gmx_MMPBSA>=1.5.6 lickit, I encountered "ERROR: Could not build wheels for mpi4py, which is required to install pyproject.toml-based projects". However, I checked that mpi4py is already installed. Could you kindly provide some suggestions?

Thanks!

**Comment by Aunity** [comment]
Try this commands:
```
pip install gmx_MMPBSA==1.6.1 unigbsa
```

**Comment by zaixizhang** [comment]
Thanks, it works for me!
